###################################################################################################
############################# ShamanOps pipeline | GitHub Actions##################################
###################################################################################################
name: ShamanOps
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  shamanops:
    uses: shamanops/resources/.github/workflows/base-cloud-rc.yaml@main
    with:
    ## Environments:
    ## full-with-drp (dev/stg/prod/drp) | full (dev/stg/prod) | mid (stg/prod) | minimal (prod)
      environments: 'full'
    # Project
      projectName: "examples"
    # Approvals
      shamanopsBusinessApprovers: 'user1@customer.com'
      shamanopsTechnicalApprovers: 'user2@customer.com'
      shamanopsBusinessApproversMinimalProd: '1'
      shamanopsTechnicalApproversMinimalProd: '1'
    # Verbosity level
      log_level: 'normal'
    # Tokens
      shamanops_customer_token: "${{secrets.shamanops_customer_token}}"
##################################################################################################
##################################################################################################
